### ISSUE TITLE
error with example

### ISSUE THREAD

**Issue by juanpide** [edwindj/ffbase2#1]
Hello, 
When I try your first example I get this error:
Error in UseMethod("rleunpack") : 
  no applicable method for 'rleunpack' applied to an object of class "list"

**Comment by edwindj** [comment]
Thanks for reporting!
Strange: it works for me.
Just to be sure: is `ffbase` also installed?

You could try the following:

```
install.packages("ffbase")
devtool::install_github("edwind/ffbase2")
```

And then check if the error is still generated...

**Comment by juanpide** [comment]
I've found the problem was with package bit, I had to reinstall it.

regards

**Comment by edwindj** [comment]
Ok, closing it

**Comment by loganylchen** [comment]
Hi there,
I have the same problem, how can I fix it.

```
Error in UseMethod("rleunpack") :
  no applicable method for 'rleunpack' applied to an object of class "list"
Calls: get.table ... as.integer -> as.integer.hi -> unsort.hi -> rleunpack
Execution halted
```
